// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://iwwvjecrvgrdyptxhnwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3d3ZqZWNydmdyZHlwdHhobndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjA1MTksImV4cCI6MjA2OTM5NjUxOX0.QtsLSAKhi6opNHtODrTbbPQP6JczGXsmIIaWX5-Kyk8";

// Enhanced logging for debugging
if (typeof window !== 'undefined') {
  const isVercel = window.location.hostname.includes('vercel.app');
  const envUrl = import.meta.env.VITE_SUPABASE_URL;
  const envKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
  
  console.log('🔍 Supabase client config:', {
    url: SUPABASE_URL,
    key: SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...' : 'MISSING',
    envUrl: envUrl || 'NOT SET - Using fallback',
    envKey: envKey ? 'Present' : 'Missing - Using fallback',
    isProduction: import.meta.env.PROD,
    isVercel: isVercel,
    hostname: window.location.hostname
  });
  
  // Warn if on Vercel and using fallback values
  if (isVercel && (!envUrl || !envKey)) {
    console.error('⚠️ VERCEL DEPLOYMENT WARNING:', {
      issue: 'Environment variables not set in Vercel',
      action: 'Go to Vercel Dashboard > Settings > Environment Variables',
      required: ['VITE_SUPABASE_URL', 'VITE_SUPABASE_ANON_KEY'],
      current: {
        usingFallbackUrl: !envUrl,
        usingFallbackKey: !envKey
      }
    });
  }
}

// Validate configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase configuration is missing!', {
    url: SUPABASE_URL,
    key: SUPABASE_PUBLISHABLE_KEY ? 'Present' : 'Missing'
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-client-info': 'time-machine-web'
    }
  }
});